apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: argo-workflows
  name: argo-server-web
  namespace: argo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 2746
    - name: https
      port: 443
      protocol: TCP
      targetPort: 2746
  selector:
    app: argo-server