apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: platform-ops
  source:
    targetRevision: main
    path: apps/cert-manager/overlays/prod
