apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: application
  namespace: crossplane
spec:
  compositeTypeRef:
    apiVersion: platform.io/v1alpha1
    kind: XApplication
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  # - name: project
  # - name: repo
  - name: namespace
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: placeholder
    patches:
    - type: PatchSet
      patchSetName: metadata
    - type: FromCompositeFieldPath
      # fromFieldPath: metadata.labels[crossplane.io/claim-name]
      fromFieldPath: spec.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      policy:
        fromFieldPath: Required
