apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xapplications.platform.io
  namespace: crossplane
spec:
  claimNames:
    kind: Application
    plural: applications
    shortNames:
    - ap
  defaultCompositionRef:
    name: application
  group: platform.io
  names:
    kind: XApplication
    plural: xapplications
    shortNames:
    - xap
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - name
            properties:
              name:
                type: string
