apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: platform-ops
  source:
    targetRevision: main
    path: apps/argo-workflows/overlays/prod
