apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/francisco-com-au/platform-apps
      revision: main
      directories:
      - path: '*'
  template:
    spec:
      source:
        targetRevision: main
        path: '{{path.basename}}/overlays/prod'
