apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  dnsNames:
    - argocd.francisco.com.au
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer