apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-ops-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/francisco-com-au/platform-apps.git
      revision: develop
      directories:
      - path: '*'
  template:
    spec:
      source:
        targetRevision: develop
        path: '{{path.basename}}/overlays/dev'
