apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one-password
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-ops
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.8.1
    chart: connect
    helm:
      releaseName: connect
      parameters:
        - name: operator.create
          value: "true"
        - name: operator.watchNamespace
          value: []
  destination:
    server: https://kubernetes.default.svc
    namespace: one-password
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true