apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xplatformapplications.platform.io
  namespace: crossplane
spec:
  claimNames:
    kind: PlatformApplication
    plural: platformapplications
    shortNames:
    - ap
  defaultCompositionRef:
    name: platformapplication
  group: platform.io
  names:
    kind: XPlatformApplication
    plural: xplatformapplications
    shortNames:
    - xap
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - name
            properties:
              name:
                type: string
